server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
        - id: book-service
          uri: http://localhost:8082/
          predicates:
            - Path=/books/**
        - id: borrowing-service
          uri: http://localhost:8083/
          predicates:
            - Path=/borrowings/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE